default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cheat-app_development
test:
  <<: *default
  database: cheat-app_test
  
production:
  <<: *default
  database: cheat-app_production
  username: cheat-app
  password: <%= ENV['CHEAT-APP_DATABASE_PASSWORD'] %>
